### ISSUE TITLE
Fetch chapter images bug?

### ISSUE THREAD

**Issue by MKS2045** [EMACC99/mangadex#16]
So i hace a problem with the fetchchapterimages method that throws me a typeerror exception:
![image](https://user-images.githubusercontent.com/102050054/159300926-f4682066-0507-49f2-8a4e-f8078e7ba5bc.png)

![image](https://user-images.githubusercontent.com/102050054/159300703-1331c114-8a30-4be6-b592-ba9181431bcf.png)
I dont know if i am doing something not correctly or something, thanks in advance
PD: I am new as python developer

**Comment by EMACC99** [comment]
It took a while trying to figure out the error, It's not a fetch chapter bug, it's in the way the chapter_list may be initialized, can you tell me how the chapter_list was initialized?

**Comment by MKS2045** [comment]
![image](https://user-images.githubusercontent.com/102050054/159336936-873ab900-36e7-4301-a16a-10a5f3706d26.png)
This?

**Comment by EMACC99** [comment]
After debugging and trying some things I discovered that there are some mangas that do not have available a certain translation available (I don't know the reason but apparently is on mangadex side) so it's returning an empty list, thus the error you are getting. To avoid the error try checking that the list length is not 0 i.e

```py
if len(chapter_list) != 0:
    for ix, chapter in enumerate(chapter_list):
        chapters.append({
        "title" : chapter.title,
        # your code
         .
         .
         .

else:
    continue #continue with the loop
```

**Comment by MKS2045** [comment]
you mean like this?
![image](https://user-images.githubusercontent.com/102050054/159350992-e431e1e1-76dc-4943-9e49-5528c83445a0.png)
Because i tried it, but it puts the same error...
![image](https://user-images.githubusercontent.com/102050054/159351103-9936fe28-4b4a-45e5-bbe6-8e0c9c281e1d.png)
And i notice another problem, it does not return all chapters. In the json where i dump the information just put a few chapters not all, why is that?
And sorry if i am irritating with this questions

**Comment by EMACC99** [comment]
Can you provide the full error, like the tracebacks and all? For the reason that it doesn't return all the chapters, I think that is because the API stopped serving some things that are copyrighted or not hosted on mangadex (the chapter has an external link). You can access all the chapters available on the index with `api.get_manga_volumes_and_chapters(manga_id = manga_id)` and it will return the chapters available

**Comment by MKS2045** [comment]
Okay so this is the full error ig:
![image](https://user-images.githubusercontent.com/102050054/159353733-3a280884-b2ce-4333-b994-e54a3c9658e9.png)

**Comment by MKS2045** [comment]
So i think im just dumb....
it appears that i was doing that inside the for loop...
sorry for waisting your time with that. I just have the last question about how to use the method get_manga_volumes
![image](https://user-images.githubusercontent.com/102050054/159367639-6d8fc25c-9fbd-4b73-8551-2553a8fbd5da.png)
Because i get all the json stuff but i dont know how to access it to get the links, or name....

**Comment by EMACC99** [comment]
I tried to replicate your issue with the following code:

```py
import mangadex

api = mangadex.Api()
random_manga_list = [api.random_manga() for _ in range(10)]

for ix, manga in enumerate(random_manga_list):
    chapt_list = api.chapter_list(manga = manga.manga_id, translatedLanguage=['en'])
    chapters = []
    if chapt_list != 0:
        for jx, chap in enumerate(chapt_list):
            chapters.append({"Chapter" : {
                "title" : chap.title,
                "lang": chap.translatedLanguage
            }})
```
but couldn't. I have no idea what is causing the problem.

the difference between `get_manga_volumes_and_chapters` and `chapter_list`, is that the first gives you just the chapter ids of just a manga and `chapter_list`  will give you from different mangas if you do not pass arguments or pass an array with manga_ids.

**Comment by MKS2045** [comment]
So, the thing is to use the method get_chapter with the id that returns the mehod get_manga_volumes_and_chapters?
But it seems it returns more than just the id
![image](https://user-images.githubusercontent.com/102050054/159369967-fb8dc860-e986-4d82-929e-655077fd14d5.png)
Like the count or others, how can i pick just the id of the chapter?
And why the other method that is chapter_list not returning the same?
Because the other one is more simple and more easy to use in my opinion
And i really wanna help because i found this api very useful, but my knowledge of english and python are quite low...

**Comment by EMACC99** [comment]
The `chapter_list` method returns a `List[Chapter]` a list of chapter objects,  currently, the `get_manga_volumes_and_chapters` just returns a JSON. The main reason that this returns a JSON is that I haven't parsed them into a Chapter object, and the way the JSON is constructed prevents me from using the  `Chapter.ChapterFromDIct` constructor that I have implemented. Just use the method that works best for you, I have the method because the API offers it. 



For the contribution part, it occurs to me that as a challenge you try to convert this JSON into a list of Chapters, you don't have to submit but I'll be glad if you send me your solution (And it may end up in the library). If you have any more questions, feel free to ask.

**Comment by MKS2045** [comment]
You mean like this?
![image](https://user-images.githubusercontent.com/102050054/159517373-a6ce8f60-d53f-47aa-966c-617fda62b9d8.png)
![image](https://user-images.githubusercontent.com/102050054/159517564-4d7df9c5-a21c-463c-99b3-bea304956917.png)
![image](https://user-images.githubusercontent.com/102050054/159517613-9979ecb5-780c-4611-92b8-250a5145f203.png)

**Comment by EMACC99** [comment]
The implementation seems fine, I just need to test it and give you an example of how to implement it directly onto the class (or if you prefer, I can do it and credit you on a comment).

For the second part, the thing is that you are exceeding the rate limits on the queries to the server https://api.mangadex.org/docs.html#section/Rate-limits you can only do 40 per minute, there you can set a timer or just fetch them as you need to.

**Comment by EMACC99** [comment]
No, the links are valid forever (unless the image server is down), the only thing that is valid for 15 minutes, is the session header when you log in

**Comment by MKS2045** [comment]
So it is normal to still having the same issue after 2 hours?
Is there an alternative to the method fetchchapterimages?
